-- MySQL Script generated by MySQL Workbench
-- gio 13 nov 2025, 15:29:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GestioLAN
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GestioLAN
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GestioLAN` DEFAULT CHARACTER SET armscii8 ;
USE `GestioLAN` ;

-- -----------------------------------------------------
-- Table `GestioLAN`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestioLAN`.`category` (
  `id_category` INT NOT NULL,
  `name_category` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `nome_categoria_UNIQUE` (`name_category` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestioLAN`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestioLAN`.`items` (
  `id_item` INT NOT NULL AUTO_INCREMENT,
  `name_category` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `id_category` INT NULL,
  `quantity` INT NOT NULL,
  `type_quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`id_item`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestioLAN`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestioLAN`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);

CREATE USER 'admin' IDENTIFIED BY 'Paswd0892!';

GRANT ALL ON `GestioLAN`.* TO 'admin';
CREATE USER 'Marco' IDENTIFIED BY 'Atlaq393!';

GRANT SELECT ON TABLE `GestioLAN`.* TO 'Marco';
GRANT SELECT, INSERT, TRIGGER ON TABLE `GestioLAN`.* TO 'Marco';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `GestioLAN`.* TO 'Marco';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
